import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {createRequire} from "node:module";
import test from "node:test";
import ts from "typescript";
const require=createRequire(import.meta.url),Module=require("module");
Module._extensions[".ts"]=(mod,filename)=>mod._compile(ts.transpileModule(readFileSync(filename,"utf8"),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,filename);
const THREE=require("three"),{applyArtworkTexture,createJewelModel}=require("../lib/jewel-model.ts"),{JEWEL_MESH,projectedFitDistance}=require("../lib/jewel-mesh.ts");
const {createDistinctPercentReporter,hasHealthyFrame,hasRenderableFrame,refitAlongCurrentView,settleControls}=require("../lib/jewel-controls.ts");
const near=(a,b,t=.02)=>assert.ok(Math.abs(a-b)<=t,`${a} ≉ ${b}`);

test("closed factory has exact standard jewel-case envelope",()=>{const m=createJewelModel(),b=new THREE.Box3().setFromObject(m.root);near(b.min.x,-71);near(b.max.x,71);near(b.min.y,0);near(b.max.y,10.4);near(b.min.z,-62.5);near(b.max.z,62.5);near(b.max.x-b.min.x,142);near(b.max.z-b.min.z,125);near(b.max.y-b.min.y,10.4);near(m.lid.position.x,-60.5);near(m.lid.position.y,6.9);assert.equal(m.root.getObjectByName("fixed-hinge-strip").parent.name,"rear-shell");m.dispose();});

test("disc is 120/15/1.2, centered at X5, and contacts tray support",()=>{const m=createJewelModel();m.root.updateMatrixWorld(true);const disc=m.root.getObjectByName("disc-substrate"),tray=m.root.getObjectByName("tray-support"),db=new THREE.Box3().setFromObject(disc),tb=new THREE.Box3().setFromObject(tray);near(db.max.x-db.min.x,120,.03);near(db.max.z-db.min.z,120,.03);near(db.max.y-db.min.y,1.2,.03);near((db.min.x+db.max.x)/2,5);near(db.min.y,tb.max.y);const pos=disc.geometry.attributes.position;let nearest=Infinity;for(let i=0;i<pos.count;i++)nearest=Math.min(nearest,Math.hypot(pos.getX(i),pos.getZ(i)));near(nearest,7.5,.03);const hub=m.root.getObjectByName("tray-hub-stem"),hb=new THREE.Box3().setFromObject(hub);assert.ok(hb.max.x<=12.2+.02&&hb.min.x>=-2.2-.02,"hub stem stays inside hole");const lip=new THREE.Box3().setFromObject(m.root.getObjectByName("tray-hub-capture-lip"));assert.ok(lip.min.y>db.max.y,"capture lip is above substrate");m.dispose();});

test("paper faces are independent, oppositely oriented, and carry named artwork roles",()=>{const m=createJewelModel();for(const role of ["front","frontInner","back","backInner","spineLeft","spineRight","label"]){assert.equal(m.artworkMaterials[role].userData.artworkRole,role);assert.equal(m.artworkMaterials[role].userData.artworkPart,role);}const normal=name=>{const mesh=m.root.getObjectByName(name),n=new THREE.Vector3(0,0,1);return n.transformDirection(mesh.matrixWorld);};m.root.updateMatrixWorld(true);assert.ok(normal("artwork-front").y>.99);assert.ok(normal("artwork-front-inner").y<-.99);assert.ok(normal("artwork-back").y<-.99);assert.ok(normal("artwork-back-inner").y>.99);assert.ok(normal("artwork-spine-left").x<-.99);assert.ok(normal("artwork-spine-right").x>.99);const inner=m.root.getObjectByName("artwork-back-inner").geometry.attributes.uv;near(inner.getX(0),6.5/150,1e-6);near(inner.getX(1),143.5/150,1e-6);m.dispose();});

test("both sides of each paper keep texture top at world negative Z without mirroring",()=>{const m=createJewelModel();m.root.updateMatrixWorld(true);const topZ=name=>{const mesh=m.root.getObjectByName(name),position=mesh.geometry.attributes.position,uv=mesh.geometry.attributes.uv,values=[];for(let i=0;i<uv.count;i++)if(uv.getY(i)>.99)values.push(new THREE.Vector3(position.getX(i),position.getY(i),position.getZ(i)).applyMatrix4(mesh.matrixWorld).z);return values.reduce((a,b)=>a+b,0)/values.length;};near(topZ("artwork-front"),-60);near(topZ("artwork-front-inner"),-60);near(topZ("artwork-back"),-59);near(topZ("artwork-back-inner"),-59);m.dispose();});

test("spine portrait UV is transposed onto physical Y by Z faces without mirroring",()=>{const m=createJewelModel(),left=m.root.getObjectByName("artwork-spine-left").geometry.attributes.uv,right=m.root.getObjectByName("artwork-spine-right").geometry.attributes.uv,expected=[[1,1],[1,0],[0,1],[0,0]];assert.deepEqual([0,1,2,3].map(i=>[left.getX(i),left.getY(i)]),expected);assert.deepEqual([0,1,2,3].map(i=>[right.getX(i),right.getY(i)]),expected);m.dispose();});

test("tray clears the paper and folded spines while retaining exact disc contact",()=>{const m=createJewelModel();m.root.updateMatrixWorld(true);const bounds=name=>new THREE.Box3().setFromObject(m.root.getObjectByName(name)),support=bounds("tray-support"),paper=bounds("back-paper-edge"),left=bounds("artwork-spine-left"),right=bounds("artwork-spine-right"),disc=bounds("disc-substrate");assert.ok(support.min.y-paper.max.y>=.1,"tray must clear back paper");assert.ok(support.min.x>left.max.x&&support.max.x<right.min.x,"tray must stay between folded spines");near(support.max.y,disc.min.y);near(support.max.x-support.min.x,136);near(support.max.z-support.min.z,121);m.dispose();});

test("raised tray deck forms a true recessed well without intersecting the disc",()=>{const m=createJewelModel();m.root.updateMatrixWorld(true);const deck=m.root.getObjectByName("tray-raised-deck"),db=new THREE.Box3().setFromObject(deck),disc=new THREE.Box3().setFromObject(m.root.getObjectByName("disc-substrate"));near(db.min.y,2.2);near(db.max.y,4);assert.ok(disc.max.y<db.max.y,"disc top remains below raised deck top");const p=deck.geometry.attributes.position;let inner=Infinity;for(let i=0;i<p.count;i++){const radius=Math.hypot(p.getX(i)-5,p.getZ(i));if(radius>40)inner=Math.min(inner,radius);}near(inner,60.15,.04);assert.ok(inner-(disc.max.x-disc.min.x)/2>=.14,"well side clears disc edge");m.dispose();});

test("closed shell walls meet continuously without exceeding the envelope",()=>{const m=createJewelModel();m.root.updateMatrixWorld(true);const bounds=name=>new THREE.Box3().setFromObject(m.root.getObjectByName(name)),rear=bounds("rear-wall-right"),lid=bounds("lid-wall-right"),fixed=bounds("fixed-hinge-strip"),connector=bounds("fixed-strip-left-connector"),whole=new THREE.Box3().setFromObject(m.root);near(rear.max.y,lid.min.y);near(rear.max.y,connector.min.y);near(connector.max.y,fixed.min.y);near(whole.min.y,0);near(whole.max.y,10.4);m.dispose();});

test("inspection and tray styles change the actual assembly",()=>{const m=createJewelModel();m.setInspection(false,true,"clear");assert.ok(m.tray.visible&&m.disc.visible);const clear=m.root.getObjectByName("tray-support").material;assert.equal(clear.depthWrite,false);m.setInspection(false,false,"black");assert.equal(m.disc.visible,false);assert.equal(m.root.getObjectByName("tray-support").material.depthWrite,true);m.setInspection(true,true,"clear");assert.equal(m.tray.visible,false);assert.equal(m.disc.visible,false);m.dispose();});

test("lid rotates about the specified hinge and opens beyond 90 degrees",()=>{const m=createJewelModel();const pivotBefore=m.lid.getWorldPosition(new THREE.Vector3());m.setLidOpen(true);near(m.lid.rotation.z,114*Math.PI/180,1e-8);m.root.updateMatrixWorld(true);const lidBox=new THREE.Box3().setFromObject(m.lid),pivotAfter=m.lid.getWorldPosition(new THREE.Vector3());assert.ok(lidBox.max.y>120);near(pivotBefore.x,pivotAfter.x);near(pivotBefore.y,pivotAfter.y);near(pivotAfter.x,-60.5);near(pivotAfter.y,6.9);m.dispose();});

test("model constants preserve print and media dimensions",()=>{assert.equal(JEWEL_MESH.disc.outerRadius*2,120);assert.equal(JEWEL_MESH.disc.innerRadius*2,15);assert.equal(JEWEL_MESH.label.outerRadius*2,116);assert.equal(JEWEL_MESH.label.innerRadius*2,23);assert.equal(JEWEL_MESH.booklet.width,120);assert.equal(JEWEL_MESH.backCard.centerWidth,137);assert.equal(JEWEL_MESH.backCard.foldWidth,6.5);});

test("loaded artwork is not multiplied by fallback material tint",()=>{const m=createJewelModel(),texture=new THREE.Texture();for(const material of Object.values(m.artworkMaterials)){applyArtworkTexture(material,texture);assert.equal(material.map,texture);assert.equal(material.color.getHex(),0xffffff);}m.dispose();texture.dispose();});

test("camera-space fitting keeps every oblique bound corner inside narrow and desktop viewports",()=>{for(const aspect of [320/480,16/10]){for(const direction of [new THREE.Vector3(0,1.35,1.7),new THREE.Vector3(1.25,1.05,1.35)]){const m=createJewelModel();m.setLidOpen(direction.x>0);m.root.updateMatrixWorld(true);const b=new THREE.Box3().setFromObject(m.root),center=b.getCenter(new THREE.Vector3()),points=[];for(const x of [b.min.x,b.max.x])for(const y of [b.min.y,b.max.y])for(const z of [b.min.z,b.max.z])points.push(new THREE.Vector3(x-center.x,y-center.y,z-center.z));direction.normalize();const distance=projectedFitDistance(points,direction,aspect,34),camera=new THREE.PerspectiveCamera(34,aspect,1,2000);camera.position.copy(direction).multiplyScalar(distance);camera.lookAt(0,0,0);camera.updateMatrixWorld(true);for(const point of points){const projected=point.clone().project(camera);assert.ok(Math.abs(projected.x)<=.88,`x clipped at aspect ${aspect}: ${projected.x}`);assert.ok(Math.abs(projected.y)<=.88,`y clipped at aspect ${aspect}: ${projected.y}`);}m.dispose();}}});

test("public OrbitControls preset transaction preserves requested zoom and clears feedback",async()=>{const{OrbitControls}=await import("three/addons/controls/OrbitControls.js"),doc={addEventListener(){},removeEventListener(){}},dom={style:{},ownerDocument:doc,addEventListener(){},removeEventListener(){},getRootNode(){return doc},getBoundingClientRect(){return{left:0,top:0,width:800,height:600}},clientWidth:800,clientHeight:600},camera=new THREE.PerspectiveCamera(34,4/3,1,2000);camera.position.set(0,0,220);const controls=new OrbitControls(camera,dom);let fit=220,zoom=1,suppress=false;const feedback=()=>{if(!suppress)zoom=THREE.MathUtils.clamp(fit/camera.position.distanceTo(controls.target),.62,1.7)};controls.addEventListener("change",feedback);controls.enableDamping=true;controls.saveState();controls.rotateLeft(1);controls.pan(20,10);controls.update();controls.autoRotate=true;fit=600;const requestedZoom=1;suppress=true;try{settleControls(controls,()=>{controls.target.set(4,5,6);camera.position.set(4,5,606);});}finally{zoom=requestedZoom;suppress=false;}const position=camera.position.clone(),target=controls.target.clone();near(camera.position.distanceTo(controls.target),600,1e-9);near(zoom,1,1e-12);assert.notEqual(camera.position.distanceTo(controls.target),600/1.7,"old-distance feedback leaked into preset placement");assert.equal(controls.enableDamping,true);assert.equal(controls.autoRotate,true);controls.autoRotate=false;controls.update();assert.ok(camera.position.distanceTo(position)<1e-9,"stale spherical delta moved preset camera");assert.ok(controls.target.distanceTo(target)<1e-9,"stale pan moved preset target");near(zoom,1,1e-12);controls.removeEventListener("change",feedback);controls.dispose();});

test("resize refit preserves orbit direction and panned target",()=>{const camera={position:new THREE.Vector3(83,71,149)},target=new THREE.Vector3(17,-4,23),before=camera.position.clone().sub(target).normalize(),savedTarget=target.clone();refitAlongCurrentView(camera,target,432);near(camera.position.distanceTo(target),432,1e-9);assert.ok(camera.position.clone().sub(target).normalize().distanceTo(before)<1e-12);assert.ok(target.distanceTo(savedTarget)<1e-12);});

test("render readiness rejects shader errors, GL errors, empty draws, and floor-only frames",()=>{const probe=(calls,error=0)=>({info:{render:{calls}},getContext:()=>({NO_ERROR:0,getError:()=>error})});assert.equal(hasRenderableFrame(probe(1),false,true),true);assert.equal(hasRenderableFrame(probe(1),true,true),false);assert.equal(hasRenderableFrame(probe(0),false,true),false);assert.equal(hasRenderableFrame(probe(1,1282),false,true),false);assert.equal(hasRenderableFrame(probe(3),false,false),false,"floor or shadow draw calls cannot mark the jewel model ready");});

test("healthy later frames may contain no visible model after the user orbits away",()=>{const probe=(calls,error=0)=>({info:{render:{calls}},getContext:()=>({NO_ERROR:0,getError:()=>error})});assert.equal(hasHealthyFrame(probe(0),false),true,"an already-ready scene may legitimately have no submitted model draw");assert.equal(hasHealthyFrame(probe(0),true),false);assert.equal(hasHealthyFrame(probe(0,1282),false),false);});

test("WebGL ready wiring requires an opaque model draw only for the first frame",()=>{const source=readFileSync(new URL("../app/album/[id]/preview/webgl-jewel.tsx",import.meta.url),"utf8");assert.match(source,/activeModel\.root\.traverse[\s\S]*renderCamera === camera && material\.transparent === false[\s\S]*modelRendered = true/);assert.match(source,/modelRendered = false;\s*renderer\.render\(scene, camera\);\s*const frameIsValid = firstFrame \? hasHealthyFrame\(renderer, shaderFailed\) : hasRenderableFrame\(renderer, shaderFailed, modelRendered\)/,"the first frame requires the model witness while later camera motion only requires a healthy context");assert.match(source,/function fail\(message: string\) \{ if \(failed \|\| abort\.signal\.aborted\)/,"late renderer callbacks cannot report failure after cleanup");assert.match(source,/catch \{\s*observer\?\.disconnect\(\);\s*abort\.abort\(\)/,"an observer that attached before initial resize failed is disconnected");});

test("zoom reporter emits the first remount value and only subsequent changes",()=>{const values=[],report=createDistinctPercentReporter(value=>values.push(value));assert.equal(report(1),true);assert.equal(report(1.004),false);assert.equal(report(1.4),true);assert.equal(report(1.4),false);assert.deepEqual(values,[100,140]);});

test("intermediate hinge animation stays framed across every preset and screen aspect", () => {
  const corners = b => [b.min.x,b.max.x].flatMap(x => [b.min.y,b.max.y].flatMap(y => [b.min.z,b.max.z].map(z => new THREE.Vector3(x,y,z))));
  for (const aspect of [320/480,16/10]) for (const direction of [[0,1.35,1.7],[1.25,1.05,1.35],[0,-1.2,-1.7],[.15,1.65,.35]]) {
    const model=createJewelModel();
    model.setLidOpen(false);
    const bounds=new THREE.Box3().setFromObject(model.root);
    model.setLidOpen(true);
    bounds.union(new THREE.Box3().setFromObject(model.root));
    const center=bounds.getCenter(new THREE.Vector3()), d=new THREE.Vector3(...direction).normalize();
    const distance=projectedFitDistance(corners(bounds).map(p=>p.sub(center)),d,aspect,34);
    const camera=new THREE.PerspectiveCamera(34,aspect,1,2000);
    camera.position.copy(center).addScaledVector(d,distance);camera.lookAt(center);camera.updateMatrixWorld(true);
    for (let degrees=0;degrees<=114;degrees+=3) {
      model.lid.rotation.z=degrees*Math.PI/180;
      for (const point of corners(new THREE.Box3().setFromObject(model.root))) {
        const projected=point.project(camera);
        assert.ok(Math.abs(projected.x)<=1&&Math.abs(projected.y)<=1,`animation clips at ${degrees}°, aspect ${aspect}`);
      }
    }
    model.dispose();
  }
});
